repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v4.4.0
  #   hooks:
  #   -   id: trailing-whitespace
  #   -   id: end-of-file-fixer
  #   -   id: check-yaml
  #   -   id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use a versão mais recente disponível
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use a versão mais recente disponível
    hooks:
      - id: isort
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0  # Use a versão mais recente disponível
    hooks:
      - id: flake8
        language_version: python3